apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: ecr-pull
      containers:
        - name: worker
          image: REPLACE_ME_ECR_URI/kube-montecarlo-jobs-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "700m"
              memory: "1024Mi"
