name: terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "apply or destroy"
        working-directory: infra
        required: true
        default: "apply"
        type: choice
        options: [apply, destroy]

permissions:
  id-token: write
  contents: read

jobs:
  tf:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      # Use GitHub Variables for region/AZ
      TF_VAR_region: ${{ vars.AWS_REGION }}
      TF_VAR_az: ${{ vars.AWS_AZ }}

      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform init
        run: terraform init -upgrade

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        if: ${{ inputs.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform destroy
        if: ${{ inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
